{{- if and .Values.test .Values.test.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: test-cloudflare-secret
type: Opaque
stringData:
  client_id: "fe47359d4fe04df0a8689fba2358c8d2.access"
  client_secret: "7ae0f15050f34f29b394495331ca28a2"
{{- end }}