apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "common.labels" . | indent 8 }}
  template:
    metadata:
      labels:
{{ include "common.labels" . | indent 12 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.metrics.enabled }}
          {{- with .Values.metrics.port }}
          ports:
            - name: metrics
              containerPort: {{ . }}
          {{- end}}
          {{- end}}
          resources:
            {{- with .Values.resources.requests }}
            requests:
              {{- with .cpu}}
              cpu: {{ . | quote }}
              {{- end }}
              {{- with .memory}}
              memory: {{ . | quote }}
              {{- end }}
            {{- end }}
            {{- with .Values.resources.limits }}
            limits:
              {{- with .cpu}}
              cpu: {{ . | quote }}
                {{- end }}
                {{- with .memory}}
              memory: {{ . | quote }}
                {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          env:
            - name: WEB_HOOK
              valueFrom:
                secretKeyRef:
                  key: webHook
                  name: {{ .Release.Name }}-secrets
          volumeMounts:
            - mountPath: /app/data
              name: {{ .Release.Name }}-claim
      volumes:
        - name: {{ .Release.Name }}-claim
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-claim