apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels: 
{{ include "common.labels" . | indent 4 }}
data:
  webHook: {{ required "webHook is required" .Values.env.webHook | b64enc }}