apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.server.port }}
  selector:
{{ include "common.labels" . | indent 4 }}