name: s3-bucket-perma-link
description: A simple web server to allow pre-defined urls to always access specific S3 bucket resources.
version: 1.0.2
appVersion: 0.2.1
apiVersion: v1
home: https://github.com/Timmi6790/charts
sources:
  - https://github.com/Timmi6790/s3-bucket-perma-link
maintainers:
  - name: Timmi6790
    email: contact@timmi6790.de