kind: ConfigMap
apiVersion: v1
metadata:
  labels:
{{ include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
data:
  SERVER.HOST: {{ required "server host is required" .Values.application.server.host | quote }}
  SERVER.PORT: {{ required "server port is required" .Values.application.server.port | quote }}
  WEBHOOK.TARGET_BASE: {{ required "target base is required" .Values.application.handler.targetBase | quote }}
  WEBHOOK.PATHS: {{ join ", " .Values.application.handler.paths }}
  LOG_LEVEL: {{ .Values.application.logLevel | quote }}
  {{- with .Values.application.sentryDsn}}
  SENTRY_DSN: {{ . | quote }}
  {{- end}}