{{- if and .Values.test .Values.test.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: test-s3-secret
type: Opaque
stringData:
  access_key: "fe47359d4fe04df0a8689fba2358c8d2.access"
  secret_key: "7ae0f15050f34f29b394495331ca28a2"
{{- end }}